services:
  # to-do-web:
  #   build:
  #     context: ./to-do-app-web
  #   volumes:
  #     - frontend-builds:/app/dist
  #   depends_on:
  #     - to-do-service
  #     - nginx

  to-do-service:
    build:
      context: ./to-do-app-service
    ports:
      - 3000:3000
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    # volumes:
    #   - frontend-builds:/usr/share/nginx/html
    depends_on:
      - to-do-service

# volumes:
#   frontend-builds:
